In [22]:
import csv
import matplotlib.pyplot as plt
import requests
from scipy import stats
import pandas as pd
import datetime

In [38]:
quakes = pd.read_csv("earthquakedata.csv")
quakestime = pd.DataFrame(quakes)
quakestime["Time"] = pd.to_datetime(quakestime["Time"],unit='ms')
quakestime = pd.DataFrame(quakestime)
quakestime["Time"] = quakestime["Time"].astype("str")
quakestime["Year"] = pd.DatetimeIndex(quakestime["Time"]).year
quakestime = quakestime[["Year","Magnitude"]]
maxquake = quakestime.groupby("Year")
maxquake = maxquake.max()
maxquake

      Magnitude
Year
1963        6.9
1968        6.0
1973        5.4
1974        5.6
1975        5.4
1976        6.4
1977        5.2
1978        4.9
1979        5.4
1980        5.3
1981        4.3
1982        4.7
1983        5.1
1984        5.3
1985        5.1
1986        5.3
1987        6.0
1988        4.8
1989        5.1
1990        5.6
1991        5.2
1992        5.6
1993        5.3
1994        5.5
1995        4.9
1996        5.6
1997        4.8
1998        5.4
1999        4.7
2000        6.5
2001        4.6
2002        5.8
2003        5.2
2004        4.7
2005        5.6
2006        4.6
2007        5.0
2008        6.3
2009        4.9
2010        5.2
2011        4.5
2012        5.5
2013        5.3
2014        5.6
2015        5.1
2016        4.6
2017        5.2
2018        5.0
2019        4.7
2020        4.9